base_url = "https://next.aaqa.dev/"
title = "Aaqa Ishtyaq"
description = "Aaqa Ishtyaq, Ramblings on programming, tech and life."
compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["static/highlight_themes"]
highlight_themes_css = [
  { theme = "tomorrow-light", filename = "hl-light.css"},
  { theme = "tomorrow-dark", filename = "hl-dark.css"},
]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
author = "Aaqa Ishtyaq"
github = "aaqaishtyaq"
twitter = "aaqaishtyaq"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
