on:
  push:
    branches:
      - trunk

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: build site
        run: nix run .#site-build

      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
